Add Stratis root filesystem blog post
stratis-storage/stratis-docs pull request #222
Opened 2021-04-12 21:37 UTC by jbaublitz

Preliminary blog post for Stratis root filesystem feature.

2021-04-13 01:05 UTC, mulkieran requested changes
Have just one request...

2021-04-15 00:55 UTC, mulkieran requested changes
Two requests, otherwise, looks fine to me.

2021-04-15 00:55 UTC, mulkieran commented on content/stratis-rootfs.md
> +transport mechanism. After evalutating several JSON RPC libraries with Unix socket
^evalutating^evaluating

2021-04-15 00:55 UTC, mulkieran commented on content/stratis-rootfs.md
> +is one major caveat: it could started but commands could not be issued. This had
^it could...^it could be started but it could not process D-Bus commands

2021-04-18 17:01 UTC, drckeefe approved these changes

2021-04-18 18:34 UTC, mulkieran reviewed
This looks fine to me.

2021-04-20 14:05 UTC, bgurney-rh commented on content/stratis-rootfs.md
> +The absense of `nofail` here is due to the fact that `nofail` causes the boot to
Spelling correction: "The absence of..."

2021-04-20 14:36 UTC, bgurney-rh approved these changes

2021-04-20 14:58 UTC, mulkieran requested changes
One last request from me...please put in a line indicating that boot from root will be available in stratisd 2.4.0. Similar to the multi-threading PR:
```
Remarks
=======
Preliminary multi-threading support will be included in the next `stratisd`
release, 2.4.0.
```

After that, it should be ready to go.

2021-04-21 13:24 UTC, bgurney-rh approved these changes

2021-04-21 13:38 UTC, mulkieran requested changes
This looks ready to me. Please close this and open a new PR for final review.

2021-04-21 17:20 UTC, closed without merging