Release notes for 2.4.1
stratis-storage/stratis-docs pull request #228
Opened 2021-05-12 17:30 UTC by mulkieran

2021-05-12 17:31 UTC, mulkieran commented
Soliciting immediate feedback...

2021-05-12 17:42 UTC, jbaublitz requested changes
Other than this one comment, this looks great!

2021-05-12 17:42 UTC, jbaublitz commented on content/stratis-release-notes-2.4.1.md
> +A user could observe the problem by finding that most commands issued by the
This wording is slightly confusing to me. Would you be okay with something along the lines of "A user could observe the behavior caused by the bug when CLI commands would either take far longer to complete than normal or the D-Bus connection would eventually time out." I'm not set on this wording, I just want to highlight both cases.

2021-05-13 02:41 UTC, drckeefe approved these changes

2021-05-13 14:41 UTC, bgurney-rh approved these changes

2021-05-15 02:18 UTC, closed without merging