add file stratis-intro.md
stratis-storage/stratis-docs pull request #255
Opened 2021-12-10 22:41 UTC by drckeefe

Draft of introduction for Stratis

2021-12-11 02:50 UTC, mulkieran requested changes
This displays just fine and ends up where desired. The commands look a little odd. It would probably sort them out better by using a "> " at the start of the commands and a "# " at the start of the descriptions of commands.

2021-12-11 02:50 UTC, mulkieran commented on content/stratis-intro.md
> +commands used for create a filesystem that encrypts data-at-rest, to the
"for create" needs to be restated.

2021-12-11 02:50 UTC, mulkieran commented on content/stratis-intro.md
> +possible.  Specifically, Stratis uses device-mapper, LUKS, XFS, Clevis, and
"XFS, Clevis" needs an "and"

2021-12-11 02:50 UTC, mulkieran commented on content/stratis-intro.md
> +command-line syntax, APIs, options, and logging.  Stratis simplifies this by
It might not be clear what "this" refers to on this line.

2021-12-11 02:50 UTC, mulkieran commented on content/stratis-intro.md
> +Stratis has also built an API for developers to implement the storage
This is the _D-Bus_ API, better to be specific here.

2021-12-11 02:50 UTC, mulkieran commented on content/stratis-intro.md
> +Get ManageObjects:
^Manage^Managed

2021-12-11 02:50 UTC, mulkieran commented on content/stratis-intro.md
> +<!-- more -->
Move this up to the location where you have "<Read more...>", @line 21. This annotation down here is interpreted by zola. "<Read more...>" is just ignored.

2021-12-15 00:38 UTC, mulkieran requested changes
Please see requested formatting changes here: https://github.com/stratis-storage/stratis-docs/pull/259. Other than that, I think it is ready. You will have to rebase to bring in recently added changes.

2021-12-15 18:51 UTC, drckeefe commented
Closing. I will post new PR

2021-12-15 18:51 UTC, closed without merging