Release notes for Stratis 3.1.0
stratis-storage/stratis-docs pull request #278
Opened 2022-05-24 13:55 UTC by mulkieran

2022-05-24 16:29 UTC, bmr-cymru requested changes
Looks good! One minor typo?

2022-05-24 16:29 UTC, bmr-cymru commented on content/stratis-release-notes-3.0.1.md
> +* A pool's MDV is mounted in a private mount namespace and remaines mounted
*remains

2022-05-24 17:48 UTC, drckeefe approved these changes

2022-05-25 03:32 UTC, mulkieran commented
rebased.

2022-05-25 03:37 UTC, merged